spring.application.name=meter-publisher
mqtt.broker-url=tcp://localhost:1883
mqtt.client-id=meter-publisher-001
mqtt.topic=meter/METER-001/energy
meter.device-id=METER-001

spring.datasource.url=jdbc:mysql://localhost:3307/meter
spring.datasource.username=meter
spring.datasource.password=meter
